export enum Action {
	ATTACK,
	BEFORE_ATTACK,
	AFTER_ATTACK,
	FIRST_ATTACK,
	AFTER_UNIT_AHEAD_ATTACK,
	BEFORE_UNIT_AHEAD_ATTACK,
	ON_FIRST_ATTACK,
	DIE,
	BEFORE_TAKE_DAMAGE,
	AFTER_TAKE_DAMAGE,
	FIRST_TAKE_DAMAGE,
	START_OF_TURN,
	END_OF_TURN
}