export enum Action {
	//runs inside game
	ATTACK = "ATTACK",
	BEFORE_ATTACK = "BEFORE_ATTACK",
	AFTER_ATTACK = "AFTER_ATTACK",
	FIRST_ATTACK = "FIRST_ATTACK",
	BEFORE_GAME = "BEFORE_GAME",
	START_OF_TURN = "START_OF_TURN",
	END_OF_TURN = "END_OF_TURN",

	//runs inside unit
	AFTER_UNIT_AHEAD_ATTACK = "AFTER_UNIT_AHEAD_ATTACK",
	AFTER_UNIT_BEHIND_ATTACK = "AFTER_UNIT_BEHIND_ATTACK",
	DIE = "DIE",
	KILLED_UNIT = "KILLED_UNIT",

	//runs inside the stats for the unit
	BEFORE_TAKE_DAMAGE = "BEFORE_TAKE_DAMAGE",
	AFTER_TAKE_DAMAGE = "AFTER_TAKE_DAMAGE",
	FIRST_TAKE_DAMAGE = "FIRST_TAKE_DAMAGE",
	DEALT_DAMAGE = "DEALT_DAMAGE",

	//runs for buffs items and debuffs
	ON_ADD = "ON_ADD",
	ON_REMOVE = "ON_REMOVE",
}